version: "3.7"

networks:
  symfony_playground_network:

services:
  app:
    build:
      context: docker/app
      dockerfile: App.DockerFile
    container_name: symfony_playground_app
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/symfony-playground"
    networks:
      - symfony_playground_network
  web:
    build:
      context: docker/web
      dockerfile: Web.DockerFile
    container_name: symfony_playground_web
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/symfony-playground"
      - "./docker/web/app.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - symfony_playground_network
  db:
    image: mongo:4.0
    container_name: symfony_playground_mongo
    ports:
      - "4406:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    networks:
      - symfony_playground_network
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_SERVER: "db"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
    networks:
      - symfony_playground_network